/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lobby.matching.engine;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        final App classUnderTest = new App();
    }
}
