/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lobby.matching.engine;

import org.junit.jupiter.api.Test;

class MatchingEngineApplicationTest {
    @Test
    void appHasAGreeting() {
        final MatchingEngineApplication classUnderTest = new MatchingEngineApplication();
    }
}
